apiVersion: apps/v1
kind: Deployment
metadata:
  name: letssee44
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letssee44
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: letssee44
    spec:
      containers:
        - name: letssee44
          image: docker.io/tanuuidp/demo:0.0.1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 200m
              memory: 256M
